# -*- coding: utf-8 -*-
"""CMSC 447 DB Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UdKSSDQ6fuoArij0LGWfPgOzJYr7gW1o
"""

!pip install mysql.connector

import mysql.connector
from mysql.connector import (connection)

#connects to db
db = connection.MySQLConnection(user='admin', password='CoolPassword123',
                                 host='pokemon-db-instance.ckqgjzzgubut.us-east-1.rds.amazonaws.com',
                                 database='pokemon_database')

#object to allow sql query
cur = db.cursor()

tests_passed = [0,0,0,0,0]

#selects first 10 pokemon to display
select_pokemon_query = "SELECT * FROM pokemon LIMIT 10"

cur.execute(select_pokemon_query)
result = cur.fetchall()
if(result):
  tests_passed[0]=1
for row in result:
  print(row)

#selects 20 pokemon that can learn flamethrower
select_flamethrower_query = "SELECT pokemon_name FROM pokemon WHERE REGEXP_LIKE(move_list, 'flamethrower') LIMIT 20"

cur.execute(select_flamethrower_query)
result = cur.fetchall()
if(result):
  tests_passed[1]=1
for row in result:
  print(row)

#selects all pokemon that are taller than 50 decimeters
select_height_query = "SELECT pokemon_name, height FROM pokemon WHERE height > 50"

#taller than 5 meteres
cur.execute(select_height_query)
result = cur.fetchall()
if(result):
  tests_passed[2]=1
for row in result:
  print(row)

cur=db.cursor()

#insert test
insert_query = "INSERT INTO pokemon (pokemon_name, pokedex_id) VALUES ('test_pokemon', 641)"
cur.execute(insert_query)

select_last5_query = "SELECT pokedex_id, pokemon_name FROM pokemon ORDER BY pokedex_id DESC LIMIT 5"
cur.execute(select_last5_query)
result = cur.fetchall()
if(result):
  tests_passed[3]=1
for row in result:
  print(row)

#delete test
delete_query = "DELETE FROM pokemon WHERE pokedex_id = '641'"
cur.execute(delete_query)

select_last5_query = "SELECT pokedex_id, pokemon_name FROM pokemon ORDER BY pokedex_id DESC LIMIT 5"
cur.execute(select_last5_query)
result = cur.fetchall()
if(result):
  tests_passed[4]=1
for row in result:
  print(row)

for i in range(len(tests_passed)):
  if tests_passed[i] == 1:
    print("Test ", i, " PASSED")
  else:
    print("Test ", i, " FAILED")